//
// Generated by I18nSyncTask on Wed Nov 03 15:48:17 PDT 2010

package memory.client;

public interface MemoryMessages extends com.google.gwt.i18n.client.Messages
{
    @Key("editTip")
    String editTip ();

    @Key("datumCreated")
    String datumCreated ();

    @Key("datumUpdated")
    String datumUpdated ();

    @Key("accessTip")
    String accessTip ();

    @Key("closeTip")
    String closeTip ();
}
