//
// Generated by I18nSyncTask on Thu Oct 28 16:49:02 PDT 2010

package memory.client;

public interface MemoryMessages extends com.google.gwt.i18n.client.Messages
{
    @Key("editTip")
    String editTip ();

    @Key("datumCreated")
    String datumCreated ();

    @Key("datumUpdated")
    String datumUpdated ();

    @Key("closeTip")
    String closeTip ();
}
