//
// Generated by I18nSyncTask on Sat Nov 06 13:06:19 PDT 2010

package memory.client;

public interface MemoryMessages extends com.google.gwt.i18n.client.Messages
{
    @Key("editTip")
    String editTip ();

    @Key("breakTip")
    String breakTip ();

    @Key("datumCreated")
    String datumCreated ();

    @Key("datumUpdated")
    String datumUpdated ();

    @Key("accessTip")
    String accessTip ();

    @Key("orderTip")
    String orderTip ();

    @Key("closeTip")
    String closeTip ();
}
